### ISSUE TITLE
webman如何实现呢？

### ISSUE THREAD

**Issue by h4ckdepy** [walkor/workerman-filemonitor#5]
webman如何实现呢？

**Comment by h4ckdepy** [comment]
主要想实现 监控目录文件生成 然后重载

**Comment by walkor** [comment]
webman自带一个monitor

**Comment by h4ckdepy** [comment]
可是那个monitor 只能监控文件更改 不能监控文件产生吧～ 还有貌似debug模式下不能自动重载 官网也没找到相关的。

**Comment by walkor** [comment]
可以监控新产生文件。workerman以debug方式运行也就是 php start.php start （不加-d）才生效。
参考webman手册必读
https://www.workerman.net/doc/webman/attention.html#%E5%B8%B8%E9%A9%BB%E5%86%85%E5%AD%98

**Comment by h4ckdepy** [comment]
谢谢您 我再看看 但我确实只有在更新文件+debug模式下才会重载

**Comment by walkor** [comment]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/6073368/186067675-9170f127-7ea6-4ec9-beac-13d80c231365.png">

<img width="715" alt="image" src="https://user-images.githubusercontent.com/6073368/186067733-2a70430a-5fd9-462d-8152-bc39dcadeea6.png">

我这里本地和服务器上都没问题。其实一般不用检测新增文件，因为它本来就没在webman内存中，需要时加载就是最新的。

**Comment by shunhua** [comment]
> <img alt="image" width="349" src="https://user-images.githubusercontent.com/6073368/186067675-9170f127-7ea6-4ec9-beac-13d80c231365.png">
> 
> <img alt="image" width="715" src="https://user-images.githubusercontent.com/6073368/186067733-2a70430a-5fd9-462d-8152-bc39dcadeea6.png">
> 
> 我这里本地和服务器上都没问题。其实一般不用检测新增文件，因为它本来就没在webman内存中，需要时加载就是最新的。

php think worker:server reload 无效？你们在生产环境下都是怎么reload 的？
